In [1]:
# NUmpy - Numerical Python
# Advantages of Numpy
#   1. Allow several Mathematical Operations
#   2. Faster Operations

In [2]:
import numpy as np

In [3]:
# list vs numpy -> time taken

In [4]:
from time import process_time

In [5]:
# time taken by a list

In [13]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time-start_time)

0.0


In [12]:
numpy_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array = [i+5 for i in numpy_array]

end_time = process_time()

print(end_time-start_time)

0.0


In [16]:
# List

list1 = [1, 2, 3, 4]
print(list1)
type(list1)

[1, 2, 3, 4]


list

In [20]:
# numpy array
a = np.array([1, 2, 3, 4])
print(a)
type(a)
a.shape

[1 2 3 4]


(4,)

In [22]:
b = np.array([(1,2,3,4),(5,6,7,8)])
b.shape

(2, 4)

In [24]:
b = np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
print(b)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [28]:
# Initial Placeholders in numpy array of zeroes
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [30]:
x = np.ones((4,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [32]:
# array of particular value 
x = np.full((5,4), 5)
print(x)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [35]:
# create a identity matrix
x = np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [38]:
# create a numpy array with random values
x = np.random.random((3,4))
print(x)

[[0.78657703 0.45642469 0.23388588 0.78025714]
 [0.39214304 0.88823025 0.86320867 0.2886489 ]
 [0.01451864 0.49972026 0.38151615 0.76752267]]


In [44]:
# random integer values array in a specific range
x = np.random.randint(10,100,(2,5))
print(x)

[[30 58 79 56 49]
 [33 56 96 50 79]]


In [46]:
# array of evenly spaced value  -> specifying the values required
x = np.linspace(10,30,5)
print(x)

[10. 15. 20. 25. 30.]


In [49]:
# array of evenly spaced values -> specifying the steps

x = np.arange(10,30,5)
print(x)

[10 15 20 25]


In [51]:
# convert a list into numpy array

list_a = [10,20,20,20,50]
np_array = np.array(list_a)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

In [54]:
# ANalysing a numpy array

x = np.random.randint(10,90,(5,5))
print(x)

[[65 17 37 31 28]
 [62 57 71 85 82]
 [33 44 17 22 75]
 [74 10 86 73 23]
 [37 31 76 14 74]]


In [56]:
# array dimension 
print(x.shape)

(5, 5)


In [58]:
# no. of dimensions
print(x.ndim)

2


In [60]:
# no. of elments in array
print(x.size)

25


In [62]:
# checking of datatype of value in array
print(x.dtype)

int32


In [63]:
# mathematical Operations on numpy array

In [66]:
list_a = [1,2,3,4,5]
list_b = [6,7,8,9,10]
print(list_a + list_b) 
# this concenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [71]:
x = np.random.randint(0,10,(3,3))
y = np.random.randint(10,20,(3,3))
print(x)
print(y)

print(x+y)
print(x-y)
print(x*y)
print(x/y)

[[3 0 1]
 [3 5 1]
 [0 3 2]]
[[17 16 12]
 [12 17 13]
 [14 15 14]]
[[20 16 13]
 [15 22 14]
 [14 18 16]]
[[-14 -16 -11]
 [ -9 -12 -12]
 [-14 -12 -12]]
[[51  0 12]
 [36 85 13]
 [ 0 45 28]]
[[0.17647059 0.         0.08333333]
 [0.25       0.29411765 0.07692308]
 [0.         0.2        0.14285714]]


In [74]:
x = np.random.randint(0,10,(3,3))
y = np.random.randint(10,20,(3,3))
print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))

[[13 15 15]
 [19 11 19]
 [13 22 22]]
[[-11 -11 -11]
 [-13  -9  -7]
 [-13  -8  -8]]
[[ 12  26  26]
 [ 48  10  78]
 [  0 105 105]]
[[0.08333333 0.15384615 0.15384615]
 [0.1875     0.1        0.46153846]
 [0.         0.46666667 0.46666667]]


In [76]:
# array manipulations

array = np.random.randint(0,10,(2,3))
print(array.shape)


(2, 3)


In [79]:
# transpose

# method 1
array = np.random.randint(0,10,(2,3))
trans = np.transpose(array)
print(trans)

# method 2
trans2 = array.T
print(trans2)

[[3 5]
 [8 3]
 [3 0]]
[[3 5]
 [8 3]
 [3 0]]


In [82]:
# reshaping array

a =  np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

b = a.reshape(3,2)
print(b)
print(b.shape)

[[5 4 0]
 [2 0 7]]
(2, 3)
[[5 4]
 [0 2]
 [0 7]]
(3, 2)


In [ ]:
# These all are the basics of numpy